name: My first program

on: push

jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: Welcome message
        run: echo "My first github action code."

      - name: list the files
        run: ls -l

      - name: Read file
        run: cat README.md
